# Generated by Django 3.0.8 on 2020-07-23 14:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from openwisp_notifications.types import NOTIFICATION_CHOICES
from swapper import get_model_name


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_users', '0009_create_organization_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openwisp_notifications', '0003_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=NOTIFICATION_CHOICES, max_length=30, null=True
                    ),
                ),
                (
                    'web',
                    models.BooleanField(
                        default=True,
                        help_text='Note: Non-superadmin users receive notifications only for organizations of which they are member of.',
                        verbose_name='web notifications',
                    ),
                ),
                (
                    'email',
                    models.BooleanField(
                        default=True,
                        help_text='Note: Non-superadmin users receive notifications only for organizations of which they are member of.',
                        verbose_name='email notifications',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=get_model_name('openwisp_users', 'Organization'),
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'user notification settings',
                'verbose_name_plural': 'user notification settings',
                'ordering': ['type', 'organization'],
                'abstract': False,
                'swappable': 'OPENWISP_NOTIFICATIONS_NOTIFICATIONSETTING_MODEL',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationsetting',
            constraint=models.UniqueConstraint(
                fields=('organization', 'type', 'user'),
                name='unique_notification_setting',
            ),
        ),
    ]
