# Generated by Django 3.0.8 on 2020-07-24 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_notifications', '0004_notificationsetting'),
    ]

    operations = [
        migrations.DeleteModel(name='NotificationUser',),
    ]
