# Generated by Django 3.0.8 on 2020-07-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_notifications', '0003_notificationsetting'),
    ]

    operations = [
        migrations.DeleteModel(name='NotificationUser',),
    ]
